export const nodeJsExternal: readonly string[] = [
  'async_hooks',
  'assert',
  'buffer',
  'child_process',
  'cluster',
  'crypto',
  'dgram',
  'dns',
  'domain',
  'events',
  'fs',
  'http',
  'http2',
  'https',
  'net',
  'os',
  'module',
  'path',
  'punycode',
  'querystring',
  'process',
  'readline',
  'stream',
  'string_decoder',
  'timers',
  'tls',
  'tty',
  'url',
  'util',
  'v8',
  'vm',
  'zlib',
].reduce((result, builtin) => {
  result.push(builtin, 'node:' + builtin);
  return result;
}, [] as string[]);
